### ISSUE TITLE
求使用教程！

### ISSUE THREAD

**Issue by jasonlin5** [nondanee/JikeRedirect-Xposed#1]
求使用教程！太小白了我

**Comment by nondanee** [comment]
哇，即刻锦鲤翻我牌子！！！

看你动态用的是魅族，那应该用不了 Xposed 呢

你直接用这个吧 https://github.com/nondanee/Jike-Patcher/releases
已经打了 patch 装上就能用

是自己签的名，和官方版不共存，要先卸载旧的哦

**Comment by jasonlin5** [comment]
非常感谢！
害，过气了，好久没有中奖了

**Comment by nondanee** [comment]
👌
