### ISSUE TITLE
你好，请问能更新1.2版本在太极中的使用吗？

### ISSUE THREAD

**Issue by veink-y** [nondanee/JikeRedirect-Xposed#2]
RT

**Comment by nondanee** [comment]
好的，已经提交了，等审核

**Comment by veink-y** [comment]
> 好的，已经提交了，等审核

另外，请教下是否必须要太极阳，我现在依然无法打开，显示网络无法连接

**Comment by nondanee** [comment]
不清楚，我没在太极里试过😂

**Comment by veink-y** [comment]
> 不清楚，我没在太极里试过😂

好吧，我再去试试

**Comment by nondanee** [comment]
我试了下会报错
```
java.lang.NoClassDefFoundError:
com.ruguoapp.jike.network.c
```

但是我在 Android 8.1 的 Official Xposed 测试过是可以用的

**Comment by nondanee** [comment]
不知道什么问题，也不知道怎么改
你没什么特殊需求的话直接用 https://github.com/nondanee/Jike-Patcher 就行了

**Comment by veink-y** [comment]
> 不知道什么问题，也不知道怎么改
> 你没什么特殊需求的话直接用 https://github.com/nondanee/Jike-Patcher 就行了

感谢，其实一直在用jellow，不过最想要的还是那个信息聚合的功能

**Comment by nondanee** [comment]
如 README 里的描述，只是接了 jellow 的 API
如果你不是 jellow 用户 (没有内测资格)，装上模块也登录不了的
jellow 的服务器并没有开放信息聚合的内容，装模块后也看不到 "逛逛圈子" 的内容

**Comment by veink-y** [comment]
> 如 README 里的描述，只是接了 jellow 的 API
> 如果你不是 jellow 用户 (没有内测资格)，装上模块也登录不了的
> jellow 的服务器并没有开放信息聚合的内容，装模块后也看不到 "逛逛圈子" 的内容
> 

Jellow内测用户ing，不过手机限制 jike-patcher暂时也无法使用，暂时我先在vmos里尝试，而且如果如你所说，那么，可能暂时也没有必须折腾的需求了

**Comment by nondanee** [comment]
手机有什么限制啊？
